version: 0.2

phases:
  pre_build:
    commands:
       - echo Logging / auth in to Amazon ECR
       - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 565428532910.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - echo Building the docker image
      - docker build -t leezonghan19/link-app .
      - docker tag leezonghan19/link-app:latest 565428532910.dkr.ecr.us-east-1.amazonaws.com/leezonghan19/link-app:latest


  post_build:
    commands:
     - echo build completed
     - echo pushing in to docker ECR...
     - docker push 565428532910.dkr.ecr.us-east-1.amazonaws.com/leezonghan19/link-app:latest
     - echo Writing image definition file..
     - printf '[{"name":"%s","imageUri":"%s"}]' "my-cluster" "565428532910.dkr.ecr.us-east-1.amazonaws.com/leezonghan19/link-app" > imagedefinitions.json


artifacts:
  files:
    - imagedefinitions.json
